/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/campaigns": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Campaigns */
        readonly get: operations["list_campaigns_api_v1_campaigns_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/campaigns/{campaign_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Campaign */
        readonly get: operations["get_campaign_api_v1_campaigns__campaign_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/chat": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Chat */
        readonly post: operations["chat_api_v1_chat_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/comparisons": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Comparisons */
        readonly post: operations["comparisons_api_v1_comparisons_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/coverage": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Coverage */
        readonly get: operations["coverage_api_v1_coverage_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/notifications": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Kampanya değişiklik bildirimlerini salt okunur listele */
        readonly get: operations["list_notifications_api_v1_notifications_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/previews/extractions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Yapıştırılan metinden doğrulanmamış çıkarım önizlemesi üret */
        readonly post: operations["preview_extraction_api_v1_previews_extractions_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health/live": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** İşlem liveness kontrolü */
        readonly get: operations["live_health_live_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Bağımlılık readiness kontrolü */
        readonly get: operations["ready_health_ready_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerCitation */
        readonly AnswerCitation: {
            /** Block Id */
            readonly block_id: string;
            /** Id */
            readonly id: string;
            /** Quote */
            readonly quote: string;
            /** Source Document Id */
            readonly source_document_id: string;
            /** Source Title */
            readonly source_title: string | null;
            /**
             * Source Url
             * Format: uri
             */
            readonly source_url: string;
            readonly status: components["schemas"]["CitationStatus"];
        };
        /**
         * CampaignChangeEvent
         * @description Public envelope for one strictly validated campaign-change outbox event.
         */
        readonly CampaignChangeEvent: {
            /** Campaign Key */
            readonly campaign_key: string;
            /**
             * Change Kind
             * @enum {string}
             */
            readonly change_kind: "created" | "updated";
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /**
             * Observed At
             * Format: date-time
             */
            readonly observed_at: string;
            /** Previous Record Id */
            readonly previous_record_id: string | null;
            /** Record Id */
            readonly record_id: string;
            readonly record_status: components["schemas"]["RecordStatus"];
            /** Record Version */
            readonly record_version: number;
        };
        /** CampaignData */
        readonly CampaignData: {
            /** Bank Id */
            readonly bank_id: string;
            readonly campaign_type: components["schemas"]["CampaignType"];
            readonly comparison_context: components["schemas"]["ComparisonContext"];
            /** Customer Segments */
            readonly customer_segments: readonly string[];
            /** Eligibility Conditions */
            readonly eligibility_conditions: readonly string[];
            /** Fees */
            readonly fees: readonly components["schemas"]["FeeValue"][];
            /** Financing Amounts */
            readonly financing_amounts: readonly components["schemas"]["MoneyValue"][];
            readonly product_family: components["schemas"]["ProductFamily"];
            /** Rates */
            readonly rates: readonly components["schemas"]["RateValue"][];
            /** Rewards */
            readonly rewards: readonly components["schemas"]["RewardValue"][];
            /** Summary */
            readonly summary: string | null;
            /** Terms */
            readonly terms: readonly components["schemas"]["TermRange"][];
            /** Title */
            readonly title: string;
            readonly validity: components["schemas"]["ValidityWindow"] | null;
        };
        /** CampaignDetail */
        readonly CampaignDetail: {
            readonly campaign: components["schemas"]["CampaignSummary"];
            /** Evidence */
            readonly evidence: readonly components["schemas"]["EvidenceProjection"][];
            readonly extraction: components["schemas"]["ExtractionProjection"];
            /** Record Sha256 */
            readonly record_sha256: string;
            /** Source Document Id */
            readonly source_document_id: string;
            /** Source Title */
            readonly source_title: string | null;
            /**
             * Source Url
             * Format: uri
             */
            readonly source_url: string;
            /** Validation Issues */
            readonly validation_issues: readonly string[];
        };
        /** CampaignFacets */
        readonly CampaignFacets: {
            /** Banks */
            readonly banks: readonly components["schemas"]["FacetOption"][];
            /** Currencies */
            readonly currencies: readonly components["schemas"]["FacetOption"][];
            /** Customer Segments */
            readonly customer_segments: readonly components["schemas"]["FacetOption"][];
            /** Product Families */
            readonly product_families: readonly components["schemas"]["FacetOption"][];
            /** Sales Channels */
            readonly sales_channels: readonly components["schemas"]["FacetOption"][];
        };
        /** CampaignListResponse */
        readonly CampaignListResponse: {
            /**
             * As Of
             * Format: date-time
             */
            readonly as_of: string;
            readonly facets: components["schemas"]["CampaignFacets"];
            /** Items */
            readonly items: readonly components["schemas"]["CampaignSummary"][];
            /** Next Cursor */
            readonly next_cursor: string | null;
        };
        /** CampaignSummary */
        readonly CampaignSummary: {
            /** Bank Id */
            readonly bank_id: string;
            /** Bank Name */
            readonly bank_name: string;
            /** Campaign Key */
            readonly campaign_key: string;
            readonly campaign_type: components["schemas"]["CampaignType"];
            /** Currency */
            readonly currency: string | null;
            /** Customer Segments */
            readonly customer_segments: readonly string[];
            /** Evidence Count */
            readonly evidence_count: number;
            /** Id */
            readonly id: string;
            /**
             * Observed At
             * Format: date-time
             */
            readonly observed_at: string;
            readonly primary_value: components["schemas"]["PrimaryValue"] | null;
            readonly product_family: components["schemas"]["ProductFamily"];
            readonly sales_channel: components["schemas"]["SalesChannel"];
            readonly status: components["schemas"]["RecordStatus"];
            /** Summary */
            readonly summary: string | null;
            /** Title */
            readonly title: string;
            readonly validity: components["schemas"]["ValidityWindow"] | null;
            /** Version */
            readonly version: number;
        };
        /**
         * CampaignType
         * @enum {string}
         */
        readonly CampaignType: "financing_rate" | "profit_share" | "installment" | "cashback" | "discount" | "points" | "fee_waiver" | "welcome" | "other" | "unknown";
        /** ChatAnswer */
        readonly ChatAnswer: {
            /** Answer */
            readonly answer: string;
            /** Citations */
            readonly citations: readonly components["schemas"]["AnswerCitation"][];
            /** Insufficient Evidence */
            readonly insufficient_evidence: boolean;
            readonly plan: components["schemas"]["ChatQueryPlan"];
            /** Warnings */
            readonly warnings: readonly string[];
        };
        /** ChatQueryPlan */
        readonly ChatQueryPlan: {
            /** Bank Ids */
            readonly bank_ids: readonly string[];
            readonly campaign_type: components["schemas"]["CampaignType"] | null;
            /** Comparison Dimensions */
            readonly comparison_dimensions: readonly components["schemas"]["ComparisonDimension"][];
            readonly intent: components["schemas"]["QueryIntent"];
            /** Keywords */
            readonly keywords: readonly string[];
            /**
             * Limit
             * @default 5
             */
            readonly limit: number;
            readonly product_family: components["schemas"]["ProductFamily"] | null;
        };
        /** ChatRequest */
        readonly ChatRequest: {
            /** As Of */
            readonly as_of?: string | null;
            /** Question */
            readonly question: string;
        };
        /**
         * CitationStatus
         * @enum {string}
         */
        readonly CitationStatus: "verified" | "missing" | "mismatch";
        /** ComparisonContext */
        readonly ComparisonContext: {
            /** Customer Segment Keys */
            readonly customer_segment_keys: readonly string[];
            /** New Customer Only */
            readonly new_customer_only: boolean | null;
            /** Product Currency */
            readonly product_currency: string | null;
            /** Product Mechanism */
            readonly product_mechanism: string | null;
            /** @default unknown */
            readonly sales_channel: components["schemas"]["SalesChannel"];
            /** Secured */
            readonly secured: boolean | null;
        };
        /**
         * ComparisonDimension
         * @enum {string}
         */
        readonly ComparisonDimension: "rate" | "term" | "fee" | "reward" | "eligibility";
        /** ComparisonItem */
        readonly ComparisonItem: {
            /** Campaign Id */
            readonly campaign_id: string;
            /** Comparable */
            readonly comparable: boolean;
            readonly dimension: components["schemas"]["ComparisonDimension"];
            /** Display Value */
            readonly display_value: string;
            /** Evidence Ids */
            readonly evidence_ids: readonly string[];
            /** Rank */
            readonly rank: number | null;
            /** Reason Code */
            readonly reason_code: string;
        };
        /** ComparisonRequest */
        readonly ComparisonRequest: {
            /** As Of */
            readonly as_of?: string | null;
            /** Campaign Ids */
            readonly campaign_ids: readonly string[];
            /** Dimensions */
            readonly dimensions: readonly components["schemas"]["ComparisonDimension"][];
        };
        /** ComparisonResponse */
        readonly ComparisonResponse: {
            /** Canonical Sha256 */
            readonly canonical_sha256: string;
            /**
             * Generated At
             * Format: date-time
             */
            readonly generated_at: string;
            /** Items */
            readonly items: readonly components["schemas"]["ComparisonItem"][];
            /** Ruleset Version */
            readonly ruleset_version: string;
            /** Warnings */
            readonly warnings: readonly string[];
        };
        /** CoverageEntry */
        readonly CoverageEntry: {
            /** Bank Id */
            readonly bank_id: string;
            /** Bank Name */
            readonly bank_name: string;
            /**
             * Campaign Count
             * @description En güncel, insan tarafından doğrulanmış kampanya kaydı sayısı; çıkarım adaylarını içermez.
             * @default 0
             */
            readonly campaign_count: number;
            /**
             * Observed At
             * Format: date-time
             */
            readonly observed_at: string;
            /** Reason */
            readonly reason: string | null;
            /**
             * Source Count
             * @default 0
             */
            readonly source_count: number;
            readonly status: components["schemas"]["CoverageStatus"];
        };
        /**
         * CoverageStatus
         * @enum {string}
         */
        readonly CoverageStatus: "success" | "not_found" | "unreachable" | "blocked" | "partial";
        /** EvidenceProjection */
        readonly EvidenceProjection: {
            /** Block Id */
            readonly block_id: string;
            /** Field Pointer */
            readonly field_pointer: string;
            /** Id */
            readonly id: string;
            /** Quote */
            readonly quote: string;
            readonly status: components["schemas"]["EvidenceStatus"];
        };
        /** EvidenceRef */
        readonly EvidenceRef: {
            /** Block Id */
            readonly block_id: string;
            /** End Char */
            readonly end_char: number;
            /** Evidence Sha256 */
            readonly evidence_sha256: string;
            /** Field Pointer */
            readonly field_pointer: string;
            /** Id */
            readonly id: string;
            /** Quote */
            readonly quote: string;
            /** Source Document Id */
            readonly source_document_id: string;
            /** Start Char */
            readonly start_char: number;
            readonly status: components["schemas"]["EvidenceStatus"];
        };
        /**
         * EvidenceStatus
         * @enum {string}
         */
        readonly EvidenceStatus: "stated" | "inferred" | "unknown" | "ambiguous";
        /** ExtractionCandidate */
        readonly ExtractionCandidate: {
            readonly data: components["schemas"]["CampaignData"];
            /** Evidence */
            readonly evidence: readonly components["schemas"]["EvidenceRef"][];
            /** Id */
            readonly id: string;
            /** Issues */
            readonly issues: readonly string[];
            readonly metadata: components["schemas"]["ExtractionMetadata"];
            /** Source Document Id */
            readonly source_document_id: string;
        };
        /** ExtractionMetadata */
        readonly ExtractionMetadata: {
            /**
             * Completed At
             * Format: date-time
             */
            readonly completed_at: string;
            /** Extractor Version */
            readonly extractor_version: string;
            readonly method: components["schemas"]["ExtractionMethod"];
            /** Model Digest */
            readonly model_digest: string | null;
            /** Model Id */
            readonly model_id: string | null;
            /** Prompt Version */
            readonly prompt_version: string | null;
            /** Schema Version */
            readonly schema_version: string;
            /**
             * Started At
             * Format: date-time
             */
            readonly started_at: string;
        };
        /**
         * ExtractionMethod
         * @enum {string}
         */
        readonly ExtractionMethod: "rule" | "llm" | "hybrid" | "manual";
        /**
         * ExtractionPreviewRequest
         * @description Bounded operator text; no URL or execution authority crosses this boundary.
         */
        readonly ExtractionPreviewRequest: {
            /** Bank Id */
            readonly bank_id: string;
            /** Text */
            readonly text: string;
        };
        /**
         * ExtractionPreviewResponse
         * @description Non-persistent candidate output that can never represent human validation.
         */
        readonly ExtractionPreviewResponse: {
            /** Accepted Model Facts */
            readonly accepted_model_facts: number;
            readonly candidate: components["schemas"]["ExtractionCandidate"] | null;
            /**
             * Human Verified
             * @default false
             * @constant
             */
            readonly human_verified: false;
            /** Input Sha256 */
            readonly input_sha256: string;
            /** Issues */
            readonly issues: readonly string[];
            /** Model Attempted */
            readonly model_attempted: boolean;
            /**
             * Persisted
             * @default false
             * @constant
             */
            readonly persisted: false;
            /**
             * Scope
             * @default unverified_preview
             * @constant
             */
            readonly scope: "unverified_preview";
            /**
             * Status
             * @enum {string}
             */
            readonly status: "needs_review" | "abstained";
        };
        /** ExtractionProjection */
        readonly ExtractionProjection: {
            /** Extractor Version */
            readonly extractor_version: string;
            readonly method: components["schemas"]["ExtractionMethod"];
            /** Model Id */
            readonly model_id: string | null;
            /** Schema Version */
            readonly schema_version: string;
        };
        /** FacetOption */
        readonly FacetOption: {
            /** Count */
            readonly count: number;
            /** Label */
            readonly label: string;
            /** Value */
            readonly value: string;
        };
        /**
         * FeeBasis
         * @enum {string}
         */
        readonly FeeBasis: "one_time" | "per_month" | "per_year" | "per_transaction" | "percent_of_amount" | "unspecified";
        /**
         * FeeKind
         * @enum {string}
         */
        readonly FeeKind: "allocation" | "annual" | "monthly" | "transaction" | "early_exit" | "other" | "unknown";
        /** FeeValue */
        readonly FeeValue: {
            readonly basis: components["schemas"]["FeeBasis"];
            /** Description */
            readonly description: string | null;
            readonly kind: components["schemas"]["FeeKind"];
            readonly money: components["schemas"]["MoneyValue"] | null;
            readonly rate: components["schemas"]["RateValue"] | null;
            /** Raw */
            readonly raw: string;
            /** @default stated */
            readonly status: components["schemas"]["EvidenceStatus"];
        };
        /**
         * GrossNetBasis
         * @enum {string}
         */
        readonly GrossNetBasis: "gross" | "net" | "unspecified";
        /** HealthChecks */
        readonly HealthChecks: {
            /**
             * Database
             * @enum {string}
             */
            readonly database: "ok" | "failed";
            /**
             * Migration
             * @enum {string}
             */
            readonly migration: "ok" | "failed" | "out_of_date";
            /**
             * Model
             * @enum {string}
             */
            readonly model: "ok" | "failed" | "not_required";
        };
        /** HealthResponse */
        readonly HealthResponse: {
            readonly checks: components["schemas"]["HealthChecks"];
            /**
             * Status
             * @enum {string}
             */
            readonly status: "ok" | "degraded";
        };
        /** LiveResponse */
        readonly LiveResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            readonly status: "ok";
        };
        /** MoneyValue */
        readonly MoneyValue: {
            /** Amount */
            readonly amount: string;
            /** Currency */
            readonly currency: string;
            /** Raw */
            readonly raw: string;
            /** @default stated */
            readonly status: components["schemas"]["EvidenceStatus"];
        };
        /** NotificationListResponse */
        readonly NotificationListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["CampaignChangeEvent"][];
            /** Next Cursor */
            readonly next_cursor: string | null;
        };
        /** PrimaryValue */
        readonly PrimaryValue: {
            /** Label */
            readonly label: string;
            /** Value */
            readonly value: string;
        };
        /** ProblemDetail */
        readonly ProblemDetail: {
            /** Code */
            readonly code: string;
            /** Correlation Id */
            readonly correlation_id: string | null;
            /** Detail */
            readonly detail: string | null;
            /** Errors */
            readonly errors: readonly {
                readonly [key: string]: unknown;
            }[];
            /** Instance */
            readonly instance: string | null;
            /** Status */
            readonly status: number;
            /** Title */
            readonly title: string;
            /**
             * Type
             * @default about:blank
             */
            readonly type: string;
        };
        /**
         * ProductFamily
         * @enum {string}
         */
        readonly ProductFamily: "financing" | "card" | "investment" | "participation_account" | "other" | "unknown";
        /**
         * QueryIntent
         * @enum {string}
         */
        readonly QueryIntent: "list" | "detail" | "compare" | "coverage" | "glossary" | "unknown";
        /**
         * RateKind
         * @enum {string}
         */
        readonly RateKind: "financing_profit_rate" | "annual_cost_rate" | "profit_share_distribution_rate" | "historical_return_rate" | "discount_rate" | "reward_rate" | "unknown";
        /**
         * RatePeriod
         * @enum {string}
         */
        readonly RatePeriod: "monthly" | "annual" | "term_total" | "unspecified";
        /** RateValue */
        readonly RateValue: {
            /** Basis Label */
            readonly basis_label: string | null;
            /** @default unspecified */
            readonly gross_net_basis: components["schemas"]["GrossNetBasis"];
            readonly kind: components["schemas"]["RateKind"];
            readonly period: components["schemas"]["RatePeriod"];
            /** Raw */
            readonly raw: string;
            /** Reference Ends On */
            readonly reference_ends_on: string | null;
            /** Reference Starts On */
            readonly reference_starts_on: string | null;
            /** @default stated */
            readonly status: components["schemas"]["EvidenceStatus"];
            /** Term Months */
            readonly term_months: number | null;
            /** Value Percent */
            readonly value_percent: string;
        };
        /**
         * RecordStatus
         * @enum {string}
         */
        readonly RecordStatus: "validated" | "needs_review" | "rejected";
        /**
         * RewardBasis
         * @enum {string}
         */
        readonly RewardBasis: "campaign_total" | "per_customer" | "per_transaction" | "per_month" | "unspecified";
        /**
         * RewardKind
         * @enum {string}
         */
        readonly RewardKind: "money" | "points" | "discount" | "free_service" | "other";
        /** RewardValue */
        readonly RewardValue: {
            /** @default unspecified */
            readonly basis: components["schemas"]["RewardBasis"];
            /** Description */
            readonly description: string | null;
            readonly kind: components["schemas"]["RewardKind"];
            readonly maximum_money: components["schemas"]["MoneyValue"] | null;
            /** Maximum Points */
            readonly maximum_points: string | null;
            readonly minimum_spend: components["schemas"]["MoneyValue"] | null;
            readonly money: components["schemas"]["MoneyValue"] | null;
            /** Points */
            readonly points: string | null;
            /** Program Name */
            readonly program_name: string | null;
            readonly rate: components["schemas"]["RateValue"] | null;
            /** Raw */
            readonly raw: string;
            /** @default stated */
            readonly status: components["schemas"]["EvidenceStatus"];
        };
        /**
         * SalesChannel
         * @enum {string}
         */
        readonly SalesChannel: "all" | "digital" | "mobile" | "web" | "branch" | "unknown";
        /** TermRange */
        readonly TermRange: {
            /** Maximum Months */
            readonly maximum_months: number;
            /** Minimum Months */
            readonly minimum_months: number | null;
            /** Raw */
            readonly raw: string;
            /** @default stated */
            readonly status: components["schemas"]["EvidenceStatus"];
        };
        /**
         * ValidityFilter
         * @enum {string}
         */
        readonly ValidityFilter: "active" | "upcoming" | "expired" | "unknown";
        /** ValidityWindow */
        readonly ValidityWindow: {
            /** Ends On */
            readonly ends_on: string | null;
            /** Raw */
            readonly raw: string;
            /** Starts On */
            readonly starts_on: string | null;
            /** @default stated */
            readonly status: components["schemas"]["EvidenceStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly list_campaigns_api_v1_campaigns_get: {
        readonly parameters: {
            readonly query?: {
                readonly as_of?: string | null;
                readonly bank_id?: string | null;
                readonly currency?: string | null;
                readonly cursor?: string | null;
                readonly customer_segment?: string | null;
                readonly limit?: number;
                readonly product_family?: components["schemas"]["ProductFamily"] | null;
                readonly sales_channel?: components["schemas"]["SalesChannel"] | null;
                readonly validity?: components["schemas"]["ValidityFilter"] | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CampaignListResponse"];
                };
            };
            /** @description Geçersiz istek */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Kaynak bulunamadı */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sözleşme doğrulama hatası */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sunucu hatası */
            readonly 500: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly get_campaign_api_v1_campaigns__campaign_id__get: {
        readonly parameters: {
            readonly query?: {
                readonly as_of?: string | null;
            };
            readonly header?: never;
            readonly path: {
                readonly campaign_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Geçersiz istek */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Kaynak bulunamadı */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sözleşme doğrulama hatası */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sunucu hatası */
            readonly 500: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly chat_api_v1_chat_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ChatRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ChatAnswer"];
                };
            };
            /** @description Geçersiz istek */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Kaynak bulunamadı */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sözleşme doğrulama hatası */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sunucu hatası */
            readonly 500: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly comparisons_api_v1_comparisons_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ComparisonRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Geçersiz istek */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Kaynak bulunamadı */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sözleşme doğrulama hatası */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sunucu hatası */
            readonly 500: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly coverage_api_v1_coverage_get: {
        readonly parameters: {
            readonly query?: {
                readonly as_of?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["CoverageEntry"][];
                };
            };
            /** @description Geçersiz istek */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Kaynak bulunamadı */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sözleşme doğrulama hatası */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sunucu hatası */
            readonly 500: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly list_notifications_api_v1_notifications_get: {
        readonly parameters: {
            readonly query?: {
                readonly cursor?: string | null;
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
            /** @description Geçersiz istek */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Kaynak bulunamadı */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sözleşme doğrulama hatası */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sunucu hatası */
            readonly 500: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly preview_extraction_api_v1_previews_extractions_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ExtractionPreviewRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ExtractionPreviewResponse"];
                };
            };
            /** @description Geçersiz istek */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Kaynak bulunamadı */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sözleşme doğrulama hatası */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sunucu hatası */
            readonly 500: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly live_health_live_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    readonly ready_health_ready_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Servis hazır değil */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
