apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: katilim-analiz
resources:
  - ../local-infra
  - ../../components/network-boundary
patches:
  - path: delete-public-egress.yaml
