"""initial PostgreSQL persistence

Revision ID: a8575e796d75
Revises:
Create Date: 2026-07-18 21:37:33.481623
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a8575e796d75"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public VERSION '1.6'")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public VERSION '1.1'")
    op.execute(
        """
        DO $$
        DECLARE
            server_major integer;
            trgm_version text;
            unaccent_version text;
        BEGIN
            server_major := current_setting('server_version_num')::integer / 10000;
            SELECT extversion INTO trgm_version FROM pg_extension WHERE extname = 'pg_trgm';
            SELECT extversion INTO unaccent_version FROM pg_extension WHERE extname = 'unaccent';
            IF server_major <> 17 THEN
                RAISE EXCEPTION 'PostgreSQL major 17 is required; found %', server_major;
            END IF;
            IF trgm_version IS DISTINCT FROM '1.6' THEN
                RAISE EXCEPTION 'pg_trgm 1.6 is required; found %', trgm_version;
            END IF;
            IF unaccent_version IS DISTINCT FROM '1.1' THEN
                RAISE EXCEPTION 'unaccent 1.1 is required; found %', unaccent_version;
            END IF;
        END
        $$
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION public.immutable_unaccent(value text)
        RETURNS text
        LANGUAGE sql
        IMMUTABLE
        PARALLEL SAFE
        STRICT
        AS $$ SELECT public.unaccent('public.unaccent', value) $$
        """
    )
    op.execute(
        "COMMENT ON FUNCTION public.immutable_unaccent(text) IS "
        "'Katılım Analiz search contract: PostgreSQL 17, unaccent 1.1; see runbook'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=191), nullable=False),
        sa.Column("password_hash", sa.String(length=500), nullable=False),
        sa.Column("roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(password_hash) >= 20",
            name=op.f("ck_auth_users_password_hash_not_plaintext"),
        ),
        sa.CheckConstraint(
            "char_length(username) BETWEEN 1 AND 191", name=op.f("ck_auth_users_username_length")
        ),
        sa.CheckConstraint(
            "failed_attempts >= 0", name=op.f("ck_auth_users_failed_attempts_nonnegative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_users")),
    )
    op.create_index(
        "uq_auth_users_username_lower",
        "auth_users",
        [sa.literal_column("lower(username)")],
        unique=True,
    )
    op.create_table(
        "comparison_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ruleset_version", sa.String(length=191), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("canonical_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comparison_snapshots")),
        sa.UniqueConstraint("request_sha256", name="uq_comparison_snapshots_request_sha256"),
    )
    op.create_index(
        "ix_comparison_snapshots_canonical_sha256",
        "comparison_snapshots",
        ["canonical_sha256"],
        unique=False,
    )
    op.create_index(
        "ix_comparison_snapshots_generated", "comparison_snapshots", ["generated_at"], unique=False
    )
    op.create_table(
        "durable_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dedupe_key", sa.String(length=191), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("leased_by", sa.String(length=191), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','running','succeeded','failed','dead')",
            name=op.f("ck_durable_jobs_job_status_known"),
        ),
        sa.CheckConstraint(
            "attempts <= max_attempts", name=op.f("ck_durable_jobs_job_attempts_bounded")
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_durable_jobs_job_attempts_nonnegative")),
        sa.CheckConstraint(
            "max_attempts > 0", name=op.f("ck_durable_jobs_job_max_attempts_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_durable_jobs")),
        sa.UniqueConstraint("kind", "dedupe_key", name="uq_durable_jobs_kind_dedupe"),
    )
    op.create_index(
        "ix_durable_jobs_claim",
        "durable_jobs",
        ["priority", "available_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued','running')"),
    )
    op.create_index(
        "ix_durable_jobs_lease_expiry", "durable_jobs", ["lease_expires_at"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=191), nullable=False),
        sa.Column("event_type", sa.String(length=191), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.String(length=191), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dedupe_key", sa.String(length=191), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("leased_by", sa.String(length=191), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_outbox_events_outbox_attempts_nonnegative")
        ),
        sa.CheckConstraint(
            "max_attempts > 0", name=op.f("ck_outbox_events_outbox_max_attempts_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("dedupe_key", name="uq_outbox_events_dedupe_key"),
    )
    op.create_index(
        "ix_outbox_events_aggregate",
        "outbox_events",
        ["aggregate_type", "aggregate_id"],
        unique=False,
    )
    op.create_index(
        "ix_outbox_events_claim",
        "outbox_events",
        ["available_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("registry_version", sa.String(length=32), nullable=False),
        sa.Column("listing_order", sa.SmallInteger(), nullable=False),
        sa.Column("legal_name", sa.String(length=500), nullable=False),
        sa.Column("homepage_url", sa.Text(), nullable=False),
        sa.Column("allowed_hosts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("digital_bank", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(allowed_hosts) = 'array'", name=op.f("ck_sources_allowed_hosts_array")
        ),
        sa.CheckConstraint("listing_order > 0", name=op.f("ck_sources_listing_order_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_index(
        "ix_sources_registry_order", "sources", ["registry_version", "listing_order"], unique=True
    )
    op.execute(
        "CREATE INDEX ix_sources_legal_name_unaccent_trgm "
        "ON sources USING gin (immutable_unaccent(legal_name) gin_trgm_ops)"
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("client_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(csrf_hash) = 64", name=op.f("ck_auth_sessions_session_csrf_hash_sha256")
        ),
        sa.CheckConstraint(
            "char_length(token_hash) = 64", name=op.f("ck_auth_sessions_session_token_hash_sha256")
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_auth_sessions_session_expiry_after_creation")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
            name=op.f("fk_auth_sessions_user_id_auth_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("token_hash", name="uq_auth_sessions_token_hash"),
    )
    op.create_index(
        "ix_auth_sessions_user_expires", "auth_sessions", ["user_id", "expires_at"], unique=False
    )
    op.create_table(
        "clean_documents",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("clean_sha256", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "language IN ('tr','unknown')", name=op.f("ck_clean_documents_document_language_known")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_clean_documents_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clean_documents")),
        sa.UniqueConstraint("clean_sha256", name="uq_clean_documents_clean_sha256"),
    )
    op.create_index(
        "ix_clean_documents_source_created",
        "clean_documents",
        ["source_id", "created_at"],
        unique=False,
    )
    op.execute(
        "CREATE INDEX ix_clean_documents_title_unaccent_trgm "
        "ON clean_documents USING gin (immutable_unaccent(title) gin_trgm_ops) "
        "WHERE title IS NOT NULL"
    )
    op.create_table(
        "coverage_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("bank_name", sa.String(length=500), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("campaign_count", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("entry_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('success','not_found','unreachable','blocked','partial')",
            name=op.f("ck_coverage_entries_coverage_status_known"),
        ),
        sa.CheckConstraint(
            "campaign_count >= 0",
            name=op.f("ck_coverage_entries_coverage_campaign_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "source_count >= 0", name=op.f("ck_coverage_entries_coverage_source_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_coverage_entries_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coverage_entries")),
        sa.UniqueConstraint("entry_sha256", name="uq_coverage_entries_entry_sha256"),
    )
    op.create_index(
        "ix_coverage_entries_source_observed",
        "coverage_entries",
        ["source_id", "observed_at", "id"],
        unique=False,
    )
    op.create_table(
        "fetch_artifacts",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("requested_url", sa.Text(), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("http_status", sa.SmallInteger(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("robots_allowed", sa.Boolean(), nullable=False),
        sa.Column("content_type", sa.String(length=500), nullable=True),
        sa.Column("etag", sa.String(length=500), nullable=True),
        sa.Column("last_modified", sa.String(length=500), nullable=True),
        sa.Column("raw_sha256", sa.String(length=64), nullable=True),
        sa.Column("raw_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("private_raw_path", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=500), nullable=True),
        sa.Column("error_detail", sa.String(length=500), nullable=True),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'success' OR "
            "(final_url IS NOT NULL AND raw_sha256 IS NOT NULL AND raw_size_bytes > 0)",
            name=op.f("ck_fetch_artifacts_successful_fetch_has_content"),
        ),
        sa.CheckConstraint(
            "status IN ('success','not_modified','blocked','failed','skipped')",
            name=op.f("ck_fetch_artifacts_fetch_status_known"),
        ),
        sa.CheckConstraint(
            "raw_size_bytes >= 0", name=op.f("ck_fetch_artifacts_raw_size_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_fetch_artifacts_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fetch_artifacts")),
        sa.UniqueConstraint("artifact_sha256", name="uq_fetch_artifacts_artifact_sha256"),
    )
    op.create_index(
        "ix_fetch_artifacts_raw_sha256", "fetch_artifacts", ["raw_sha256"], unique=False
    )
    op.create_index(
        "ix_fetch_artifacts_source_fetched",
        "fetch_artifacts",
        ["source_id", "fetched_at"],
        unique=False,
    )
    op.create_table(
        "campaign_records",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("campaign_key", sa.String(length=191), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source_document_id", sa.String(length=191), nullable=False),
        sa.Column("bank_id", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("product_family", sa.String(length=64), nullable=False),
        sa.Column("campaign_type", sa.String(length=64), nullable=False),
        sa.Column("product_currency", sa.String(length=3), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("rate_min", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("rate_max", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("amount_min", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("amount_max", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("term_min", sa.Integer(), nullable=True),
        sa.Column("term_max", sa.Integer(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("validation_issues", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('turkish'::regconfig, "
                "immutable_unaccent((((COALESCE(title, ''::character varying))::text || "
                "' '::text) || (COALESCE(summary, ''::character varying))::text)))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('validated','needs_review','rejected')",
            name=op.f("ck_campaign_records_record_status_known"),
        ),
        sa.CheckConstraint(
            "term_max IS NULL OR term_max >= 0",
            name=op.f("ck_campaign_records_term_max_nonnegative"),
        ),
        sa.CheckConstraint(
            "term_min IS NULL OR term_min >= 0",
            name=op.f("ck_campaign_records_term_min_nonnegative"),
        ),
        sa.CheckConstraint(
            "valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_campaign_records_record_validity_ordered"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_campaign_records_record_version_positive")),
        sa.ForeignKeyConstraint(
            ["bank_id"], ["sources.id"], name=op.f("fk_campaign_records_bank_id_sources")
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["clean_documents.id"],
            name=op.f("fk_campaign_records_source_document_id_clean_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_records")),
        sa.UniqueConstraint(
            "campaign_key", "record_sha256", name="uq_campaign_records_key_record_hash"
        ),
        sa.UniqueConstraint("campaign_key", "version", name="uq_campaign_records_key_version"),
        sa.UniqueConstraint(
            "campaign_key",
            "payload_sha256",
            name="uq_campaign_records_key_payload_hash",
        ),
    )
    op.create_index(
        "ix_campaign_records_bank_observed",
        "campaign_records",
        ["bank_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_campaign_records_data_jsonb",
        "campaign_records",
        ["data"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"data": "jsonb_path_ops"},
    )
    op.create_index(
        "ix_campaign_records_family_type",
        "campaign_records",
        ["product_family", "campaign_type"],
        unique=False,
    )
    op.create_index(
        "ix_campaign_records_logical_latest",
        "campaign_records",
        [
            "campaign_key",
            sa.literal_column("observed_at DESC"),
            sa.literal_column("version DESC"),
            "id",
        ],
        unique=False,
    )
    op.create_index(
        "ix_campaign_records_search_vector",
        "campaign_records",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.execute(
        "CREATE INDEX ix_campaign_records_title_unaccent_trgm "
        "ON campaign_records USING gin (immutable_unaccent(title) gin_trgm_ops)"
    )
    op.create_table(
        "extraction_candidates",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("source_document_id", sa.String(length=191), nullable=False),
        sa.Column("bank_id", sa.String(length=64), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("extractor_version", sa.String(length=191), nullable=False),
        sa.Column("schema_version", sa.String(length=191), nullable=False),
        sa.Column("prompt_version", sa.String(length=191), nullable=True),
        sa.Column("model_id", sa.String(length=191), nullable=True),
        sa.Column("model_digest", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("issues", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("candidate_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('rule','llm','hybrid','manual')",
            name=op.f("ck_extraction_candidates_extraction_method_known"),
        ),
        sa.CheckConstraint(
            "completed_at >= started_at",
            name=op.f("ck_extraction_candidates_extraction_times_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["bank_id"], ["sources.id"], name=op.f("fk_extraction_candidates_bank_id_sources")
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["clean_documents.id"],
            name=op.f("fk_extraction_candidates_source_document_id_clean_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_candidates")),
        sa.UniqueConstraint("candidate_sha256", name="uq_extraction_candidates_candidate_sha256"),
    )
    op.create_index(
        "ix_extraction_candidates_document",
        "extraction_candidates",
        ["source_document_id"],
        unique=False,
    )
    op.create_table(
        "fetch_document_links",
        sa.Column("fetch_artifact_id", sa.String(length=191), nullable=False),
        sa.Column("document_id", sa.String(length=191), nullable=False),
        sa.Column("cleaned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cleaner_version", sa.String(length=191), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["clean_documents.id"],
            name=op.f("fk_fetch_document_links_document_id_clean_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fetch_artifact_id"],
            ["fetch_artifacts.id"],
            name=op.f("fk_fetch_document_links_fetch_artifact_id_fetch_artifacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "fetch_artifact_id", "document_id", name=op.f("pk_fetch_document_links")
        ),
    )
    op.create_table(
        "source_blocks",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("document_id", sa.String(length=191), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("locator", sa.Text(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('turkish'::regconfig, immutable_unaccent(COALESCE(text, ''::text)))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('heading','paragraph','list_item','table','metadata','other')",
            name=op.f("ck_source_blocks_block_kind_known"),
        ),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_source_blocks_block_ordinal_nonnegative")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["clean_documents.id"],
            name=op.f("fk_source_blocks_document_id_clean_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_blocks")),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_source_blocks_document_ordinal"),
        sa.UniqueConstraint("id", "document_id", name="uq_source_blocks_id_document"),
    )
    op.create_index("ix_source_blocks_document", "source_blocks", ["document_id"], unique=False)
    op.create_index(
        "ix_source_blocks_search_vector",
        "source_blocks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "comparison_record_links",
        sa.Column("comparison_id", sa.Uuid(), nullable=False),
        sa.Column("record_id", sa.String(length=191), nullable=False),
        sa.ForeignKeyConstraint(
            ["comparison_id"],
            ["comparison_snapshots.id"],
            name=op.f("fk_comparison_record_links_comparison_id_comparison_snapshots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["campaign_records.id"],
            name=op.f("fk_comparison_record_links_record_id_campaign_records"),
        ),
        sa.PrimaryKeyConstraint(
            "comparison_id", "record_id", name=op.f("pk_comparison_record_links")
        ),
    )
    op.create_table(
        "evidence_refs",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("field_pointer", sa.String(length=500), nullable=False),
        sa.Column("source_document_id", sa.String(length=191), nullable=False),
        sa.Column("block_id", sa.String(length=191), nullable=False),
        sa.Column("quote", sa.String(length=1000), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=False),
        sa.Column("end_char", sa.Integer(), nullable=False),
        sa.Column("evidence_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("ref_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "status IN ('stated','inferred','unknown','ambiguous')",
            name=op.f("ck_evidence_refs_evidence_status_known"),
        ),
        sa.CheckConstraint(
            "end_char - start_char = char_length(quote)",
            name=op.f("ck_evidence_refs_evidence_span_matches_quote"),
        ),
        sa.CheckConstraint(
            "end_char > start_char", name=op.f("ck_evidence_refs_evidence_span_ordered")
        ),
        sa.CheckConstraint(
            "start_char >= 0", name=op.f("ck_evidence_refs_evidence_start_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["block_id", "source_document_id"],
            ["source_blocks.id", "source_blocks.document_id"],
            name="fk_evidence_block_document",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_refs")),
        sa.UniqueConstraint("ref_sha256", name="uq_evidence_refs_ref_sha256"),
    )
    op.create_index(
        "ix_evidence_refs_document_block",
        "evidence_refs",
        ["source_document_id", "block_id"],
        unique=False,
    )
    op.create_table(
        "extraction_evidence",
        sa.Column("extraction_id", sa.String(length=191), nullable=False),
        sa.Column("evidence_id", sa.String(length=191), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence_refs.id"],
            name=op.f("fk_extraction_evidence_evidence_id_evidence_refs"),
        ),
        sa.ForeignKeyConstraint(
            ["extraction_id"],
            ["extraction_candidates.id"],
            name=op.f("fk_extraction_evidence_extraction_id_extraction_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "extraction_id", "evidence_id", name=op.f("pk_extraction_evidence")
        ),
    )
    op.create_table(
        "record_evidence",
        sa.Column("record_id", sa.String(length=191), nullable=False),
        sa.Column("evidence_id", sa.String(length=191), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence_refs.id"],
            name=op.f("fk_record_evidence_evidence_id_evidence_refs"),
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["campaign_records.id"],
            name=op.f("fk_record_evidence_record_id_campaign_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("record_id", "evidence_id", name=op.f("pk_record_evidence")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("record_evidence")
    op.drop_table("extraction_evidence")
    op.drop_index("ix_evidence_refs_document_block", table_name="evidence_refs")
    op.drop_table("evidence_refs")
    op.drop_table("comparison_record_links")
    op.drop_index(
        "ix_source_blocks_search_vector", table_name="source_blocks", postgresql_using="gin"
    )
    op.drop_index("ix_source_blocks_document", table_name="source_blocks")
    op.drop_table("source_blocks")
    op.drop_table("fetch_document_links")
    op.drop_index("ix_extraction_candidates_document", table_name="extraction_candidates")
    op.drop_table("extraction_candidates")
    op.drop_index(
        "ix_campaign_records_search_vector", table_name="campaign_records", postgresql_using="gin"
    )
    op.drop_index("ix_campaign_records_title_unaccent_trgm", table_name="campaign_records")
    op.drop_index("ix_campaign_records_logical_latest", table_name="campaign_records")
    op.drop_index("ix_campaign_records_family_type", table_name="campaign_records")
    op.drop_index(
        "ix_campaign_records_data_jsonb",
        table_name="campaign_records",
        postgresql_using="gin",
        postgresql_ops={"data": "jsonb_path_ops"},
    )
    op.drop_index("ix_campaign_records_bank_observed", table_name="campaign_records")
    op.drop_table("campaign_records")
    op.drop_index("ix_fetch_artifacts_source_fetched", table_name="fetch_artifacts")
    op.drop_index("ix_fetch_artifacts_raw_sha256", table_name="fetch_artifacts")
    op.drop_table("fetch_artifacts")
    op.drop_index("ix_coverage_entries_source_observed", table_name="coverage_entries")
    op.drop_table("coverage_entries")
    op.drop_index("ix_clean_documents_source_created", table_name="clean_documents")
    op.drop_index("ix_clean_documents_title_unaccent_trgm", table_name="clean_documents")
    op.drop_table("clean_documents")
    op.drop_index("ix_auth_sessions_user_expires", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index("ix_sources_registry_order", table_name="sources")
    op.drop_index("ix_sources_legal_name_unaccent_trgm", table_name="sources")
    op.drop_table("sources")
    op.drop_index(
        "ix_outbox_events_claim",
        table_name="outbox_events",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_index("ix_outbox_events_aggregate", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("ix_durable_jobs_lease_expiry", table_name="durable_jobs")
    op.drop_index(
        "ix_durable_jobs_claim",
        table_name="durable_jobs",
        postgresql_where=sa.text("status IN ('queued','running')"),
    )
    op.drop_table("durable_jobs")
    op.drop_index("ix_comparison_snapshots_generated", table_name="comparison_snapshots")
    op.drop_index("ix_comparison_snapshots_canonical_sha256", table_name="comparison_snapshots")
    op.drop_table("comparison_snapshots")
    op.drop_index("uq_auth_users_username_lower", table_name="auth_users")
    op.drop_table("auth_users")
    op.execute("DROP FUNCTION IF EXISTS public.immutable_unaccent(text)")
    # Extensions are cluster capabilities and may be shared by other schemas/applications.
    # A downgrade therefore removes only objects owned by this application.
    # ### end Alembic commands ###
